PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE "socialiniai"("Nr." INTEGER, "Miestas/Gyvenvietė" TEXT, "Gatvė" TEXT, "Namo Nr." TEXT, "Buto Nr." TEXT, "Tipas" TEXT, "Plotas" TEXT, "COL7" TEXT);
INSERT INTO "socialiniai" VALUES(1,'Panevėžio m.','Algirdo g.','54','8','Socialinis būstas','"30','64"');
INSERT INTO "socialiniai" VALUES(2,'Panevėžio m.','Aukštaičių g.','2','88','Socialinis būstas','"29','86"');
INSERT INTO "socialiniai" VALUES(3,'Panevėžio m.','Aukštaičių g.','66','41','Socialinis būstas','"19','60"');
INSERT INTO "socialiniai" VALUES(4,'Panevėžio m.','Aukštaičių g.','76','2','Socialinis būstas','"33','26"');
INSERT INTO "socialiniai" VALUES(5,'Panevėžio m.','Aukštaičių g.','76','32','Socialinis būstas','"49','98"');
INSERT INTO "socialiniai" VALUES(6,'Panevėžio m.','Ateities g.','14','5','Socialinis būstas','"35','93"');
INSERT INTO "socialiniai" VALUES(7,'Panevėžio m.','Ateities g.','18','15','Socialinis būstas','"49','88"');
INSERT INTO "socialiniai" VALUES(8,'Panevėžio m.','Ateities g.','28','24','Socialinis būstas','"63','71"');
INSERT INTO "socialiniai" VALUES(9,'Panevėžio m.','Ateities g.','34','41','Socialinis būstas','"50','80"');
INSERT INTO "socialiniai" VALUES(10,'Panevėžio m.','J. Basanavičiaus g.','1','96','Socialinis būstas','"29','25"');
INSERT INTO "socialiniai" VALUES(11,'Panevėžio m.','J. Basanavičiaus g.','52A','92','Socialinis būstas','"44','36"');
INSERT INTO "socialiniai" VALUES(12,'Panevėžio m.','J. Basanavičiaus g.','66','44','Socialinis būstas','"34','06"');
INSERT INTO "socialiniai" VALUES(13,'Panevėžio m.','Beržų g.','21','41','Socialinis būstas','"30','39"');
INSERT INTO "socialiniai" VALUES(14,'Panevėžio m.','Beržų g.','35','23','Socialinis būstas','"35','25"');
INSERT INTO "socialiniai" VALUES(15,'Panevėžio m.','Beržų g.','35','25','Socialinis būstas','"17','19"');
INSERT INTO "socialiniai" VALUES(16,'Panevėžio m.','Beržų g.','35','25','Socialinis būstas','"17','30"');
INSERT INTO "socialiniai" VALUES(17,'Panevėžio m.','F. Vaitkaus g.','9','73','Socialinis būstas','"30','43"');
INSERT INTO "socialiniai" VALUES(18,'Panevėžio m.','Danutės g.','40','43','Socialinis būstas','"50','11"');
INSERT INTO "socialiniai" VALUES(19,'Panevėžio m.','Dariaus ir Girėno g.','20','29','Socialinis būstas','"35','83"');
INSERT INTO "socialiniai" VALUES(20,'Panevėžio m.','Dariaus ir Girėno g.','39','59','Socialinis būstas','"36','37"');
INSERT INTO "socialiniai" VALUES(21,'Panevėžio m.','Dariaus ir Girėno g.','9','43','Socialinis būstas','"32','99"');
INSERT INTO "socialiniai" VALUES(22,'Panevėžio m.','Dariaus ir Girėno g.','9','91','Socialinis būstas','"33','23"');
INSERT INTO "socialiniai" VALUES(23,'Panevėžio m.','A. Smetonos g.','47','2','Socialinis būstas','"24','13"');
INSERT INTO "socialiniai" VALUES(24,'Panevėžio m.','Durpyno g.','4','36','Socialinis būstas','"28','42"');
INSERT INTO "socialiniai" VALUES(25,'Panevėžio m.','Gražinos g.','3','59','Socialinis būstas','"30','34"');
INSERT INTO "socialiniai" VALUES(26,'Panevėžio m.','J. Janonio g.','10','1','Socialinis būstas','"33','45"');
INSERT INTO "socialiniai" VALUES(27,'Panevėžio m.','J. Janonio g.','10','10','Socialinis būstas','"48','37"');
INSERT INTO "socialiniai" VALUES(28,'Panevėžio m.','J. Janonio g.','10','12','Socialinis būstas','"48','03"');
INSERT INTO "socialiniai" VALUES(29,'Panevėžio m.','J. Janonio g.','10','13','Socialinis būstas','"48','28"');
INSERT INTO "socialiniai" VALUES(30,'Panevėžio m.','J. Janonio g.','10','14','Socialinis būstas','"47','98"');
INSERT INTO "socialiniai" VALUES(31,'Panevėžio m.','J. Janonio g.','10','15','Socialinis būstas','"34','15"');
INSERT INTO "socialiniai" VALUES(32,'Panevėžio m.','J. Janonio g.','10','16','Socialinis būstas','"27','70"');
INSERT INTO "socialiniai" VALUES(33,'Panevėžio m.','J. Janonio g.','10','17','Socialinis būstas','"33','46"');
INSERT INTO "socialiniai" VALUES(34,'Panevėžio m.','J. Janonio g.','10','18','Socialinis būstas','"35','23"');
INSERT INTO "socialiniai" VALUES(35,'Panevėžio m.','J. Janonio g.','10','19','Socialinis būstas','"28','90"');
INSERT INTO "socialiniai" VALUES(36,'Panevėžio m.','J. Janonio g.','10','20','Socialinis būstas','"33','41"');
INSERT INTO "socialiniai" VALUES(37,'Panevėžio m.','J. Janonio g.','10','3','Socialinis būstas','"33','66"');
INSERT INTO "socialiniai" VALUES(38,'Panevėžio m.','J. Janonio g.','10','4','Socialinis būstas','"33','89"');
INSERT INTO "socialiniai" VALUES(39,'Panevėžio m.','J. Janonio g.','10','7','Socialinis būstas','"48','26"');
INSERT INTO "socialiniai" VALUES(40,'Panevėžio m.','J. Janonio g.','10','8','Socialinis būstas','"46','77"');
INSERT INTO "socialiniai" VALUES(41,'Panevėžio m.','J. Janonio g.','8','10','Socialinis būstas','"48','84"');
INSERT INTO "socialiniai" VALUES(42,'Panevėžio m.','J. Janonio g.','8','11','Socialinis būstas','"33','29"');
INSERT INTO "socialiniai" VALUES(43,'Panevėžio m.','J. Janonio g.','8','3','Socialinis būstas','"43','69"');
INSERT INTO "socialiniai" VALUES(44,'Panevėžio m.','J. Janonio g.','8','4','Socialinis būstas','"32','84"');
INSERT INTO "socialiniai" VALUES(45,'Panevėžio m.','J. Janonio g.','8','5','Socialinis būstas','"32','21"');
INSERT INTO "socialiniai" VALUES(46,'Panevėžio m.','J. Janonio g.','8','6','Socialinis būstas','"45','50"');
INSERT INTO "socialiniai" VALUES(47,'Panevėžio m.','J. Janonio g.','8','8','Socialinis būstas','"32','23"');
INSERT INTO "socialiniai" VALUES(48,'Panevėžio m.','J. Janonio g.','8','9','Socialinis būstas','"31','54"');
INSERT INTO "socialiniai" VALUES(49,'Panevėžio m.','Kaštonų g.','2','48','Socialinis būstas','"44','20"');
INSERT INTO "socialiniai" VALUES(50,'Panevėžio m.','Klaipėdos g.','104','48','Socialinis būstas','"44','46"');
INSERT INTO "socialiniai" VALUES(51,'Panevėžio m.','Klaipėdos g.','128','9','Socialinis būstas','"64','57"');
INSERT INTO "socialiniai" VALUES(52,'Panevėžio m.','Klaipėdos g.','34','17','Socialinis būstas','"49','90"');
INSERT INTO "socialiniai" VALUES(53,'Panevėžio m.','Klaipėdos g.','40','5','Socialinis būstas','"27','41"');
INSERT INTO "socialiniai" VALUES(54,'Panevėžio m.','Liepų al.','17','9','Socialinis būstas','"15','46"');
INSERT INTO "socialiniai" VALUES(55,'Panevėžio m.','Liepų al.','7A','1','Socialinis būstas','"28','68"');
INSERT INTO "socialiniai" VALUES(56,'Panevėžio m.','Molainių g.','14','55','Socialinis būstas','"32','83"');
INSERT INTO "socialiniai" VALUES(57,'Panevėžio m.','Molainių g.','22','17','Socialinis būstas','"35','93"');
INSERT INTO "socialiniai" VALUES(58,'Panevėžio m.','Molainių g.','28','44','Socialinis būstas','"36','13"');
INSERT INTO "socialiniai" VALUES(59,'Panevėžio m.','Molainių g.','56','14','Socialinis būstas','"36','06"');
INSERT INTO "socialiniai" VALUES(60,'Panevėžio m.','Molainių g.','56','42','Socialinis būstas','"31','35"');
INSERT INTO "socialiniai" VALUES(61,'Panevėžio m.','Molainių g.','56','50','Socialinis būstas','"31','66"');
INSERT INTO "socialiniai" VALUES(62,'Panevėžio m.','Marių g.','17','2','Socialinis būstas','"36','33"');
INSERT INTO "socialiniai" VALUES(63,'Panevėžio m.','Marių g.','22','1','Socialinis būstas','"44','74"');
INSERT INTO "socialiniai" VALUES(64,'Panevėžio m.','Marijonų g.','29','10','Socialinis būstas','"20','29"');
INSERT INTO "socialiniai" VALUES(65,'Panevėžio m.','Marijonų g.','29','13','Socialinis būstas','"30','74"');
INSERT INTO "socialiniai" VALUES(66,'Panevėžio m.','Marijonų g.','29','34','Socialinis būstas','"20','31"');
INSERT INTO "socialiniai" VALUES(67,'Panevėžio m.','Marijonų g.','29','97','Socialinis būstas','"30','22"');
INSERT INTO "socialiniai" VALUES(68,'Panevėžio m.','Margirio g.','11','15','Socialinis būstas','"56','15"');
INSERT INTO "socialiniai" VALUES(69,'Panevėžio m.','Margirio g.','11','3','Socialinis būstas','"56','18"');
INSERT INTO "socialiniai" VALUES(70,'Panevėžio m.','Margirio g.','11','6','Socialinis būstas','"56','39"');
INSERT INTO "socialiniai" VALUES(71,'Panevėžio m.','Margirio g.','11','7','Socialinis būstas','"56','08"');
INSERT INTO "socialiniai" VALUES(72,'Panevėžio m.','Margirio g.','11','9','Socialinis būstas','"56','42"');
INSERT INTO "socialiniai" VALUES(73,'Panevėžio m.','Margirio g.','9','10','Socialinis būstas','"42','97"');
INSERT INTO "socialiniai" VALUES(74,'Panevėžio m.','Margirio g.','9','8','Socialinis būstas','"83','36"');
INSERT INTO "socialiniai" VALUES(75,'Panevėžio m.','Nevėžio g.','36','51','Socialinis būstas','"26','38"');
INSERT INTO "socialiniai" VALUES(76,'Panevėžio m.','Nemuno g.','16','54','Socialinis būstas','"35','48"');
INSERT INTO "socialiniai" VALUES(77,'Panevėžio m.','Nemuno g.','80','56','Socialinis būstas','"38','04"');
INSERT INTO "socialiniai" VALUES(78,'Panevėžio m.','Prekybos g.','21','20','Socialinis būstas','"60','47"');
INSERT INTO "socialiniai" VALUES(79,'Panevėžio m.','Prekybos g.','3','20','Socialinis būstas','"49','40"');
INSERT INTO "socialiniai" VALUES(80,'Panevėžio m.','Parko g.','37','137','Socialinis būstas','"45','76"');
INSERT INTO "socialiniai" VALUES(81,'Panevėžio m.','Parko g.','45','2','Socialinis būstas','"36','30"');
INSERT INTO "socialiniai" VALUES(82,'Panevėžio m.','Parko g.','51','18','Socialinis būstas','"64','28"');
INSERT INTO "socialiniai" VALUES(83,'Panevėžio m.','Parko g.','59','13','Socialinis būstas','"49','88"');
INSERT INTO "socialiniai" VALUES(84,'Panevėžio m.','Parko g.','77','24','Socialinis būstas','"65','30"');
INSERT INTO "socialiniai" VALUES(85,'Panevėžio m.','Parko g.','97','14','Socialinis būstas','"33','31"');
INSERT INTO "socialiniai" VALUES(86,'Panevėžio m.','Ramygalos g.','112','31','Socialinis būstas','"36','53"');
INSERT INTO "socialiniai" VALUES(87,'Panevėžio m.','Ramygalos g.','57','101','Socialinis būstas','"20','55"');
INSERT INTO "socialiniai" VALUES(88,'Panevėžio m.','Ramygalos g.','67','29','Socialinis būstas','"20','34"');
INSERT INTO "socialiniai" VALUES(89,'Panevėžio m.','Ramygalos g.','67','64','Socialinis būstas','"29','98"');
INSERT INTO "socialiniai" VALUES(90,'Panevėžio m.','Respublikos g.','17','17','Socialinis būstas','"70','51"');
INSERT INTO "socialiniai" VALUES(91,'Panevėžio m.','Respublikos g.','57','6','Socialinis būstas','"34','69"');
INSERT INTO "socialiniai" VALUES(92,'Panevėžio m.','Skaistakalnio g.','1','2','Socialinis būstas','"25','46"');
INSERT INTO "socialiniai" VALUES(93,'Panevėžio m.','Sodų g.','18','33','Socialinis būstas','"29','51"');
INSERT INTO "socialiniai" VALUES(94,'Panevėžio m.','Sodų g.','21','9','Socialinis būstas','"24','75"');
INSERT INTO "socialiniai" VALUES(95,'Panevėžio m.','Sodų g.','50','24','Socialinis būstas','"29','85"');
INSERT INTO "socialiniai" VALUES(96,'Panevėžio m.','Statybininkų g.','18','23','Socialinis būstas','"35','68"');
INSERT INTO "socialiniai" VALUES(97,'Panevėžio m.','Statybininkų g.','20','50','Socialinis būstas','"38','49"');
INSERT INTO "socialiniai" VALUES(98,'Panevėžio m.','Statybininkų g.','20','74','Socialinis būstas','"38','49"');
INSERT INTO "socialiniai" VALUES(99,'Panevėžio m.','Statybininkų g.','3','98','Socialinis būstas','"44','36"');
INSERT INTO "socialiniai" VALUES(100,'Panevėžio m.','Staniūnų g.','70','10','Socialinis būstas','"59','52"');
INSERT INTO "socialiniai" VALUES(101,'Panevėžio m.','Staniūnų g.','70','11','Socialinis būstas','"60','25"');
INSERT INTO "socialiniai" VALUES(102,'Panevėžio m.','Staniūnų g.','70','12','Socialinis būstas','"69','19"');
INSERT INTO "socialiniai" VALUES(103,'Panevėžio m.','Staniūnų g.','70','13','Socialinis būstas','"61','74"');
INSERT INTO "socialiniai" VALUES(104,'Panevėžio m.','Staniūnų g.','70','14','Socialinis būstas','"47','73"');
INSERT INTO "socialiniai" VALUES(105,'Panevėžio m.','Staniūnų g.','70','16','Socialinis būstas','"62','24"');
INSERT INTO "socialiniai" VALUES(106,'Panevėžio m.','Staniūnų g.','70','17','Socialinis būstas','"56','07"');
INSERT INTO "socialiniai" VALUES(107,'Panevėžio m.','Staniūnų g.','70','18','Socialinis būstas','"59','90"');
INSERT INTO "socialiniai" VALUES(108,'Panevėžio m.','Staniūnų g.','70','20','Socialinis būstas','"69','89"');
INSERT INTO "socialiniai" VALUES(109,'Panevėžio m.','Staniūnų g.','70','23','Socialinis būstas','"79','07"');
INSERT INTO "socialiniai" VALUES(110,'Panevėžio m.','Staniūnų g.','70','25','Socialinis būstas','"56','42"');
INSERT INTO "socialiniai" VALUES(111,'Panevėžio m.','Staniūnų g.','70','26','Socialinis būstas','"59','05"');
INSERT INTO "socialiniai" VALUES(112,'Panevėžio m.','Staniūnų g.','70','27','Socialinis būstas','"58','80"');
INSERT INTO "socialiniai" VALUES(113,'Panevėžio m.','Staniūnų g.','70','28','Socialinis būstas','"69','11"');
INSERT INTO "socialiniai" VALUES(114,'Panevėžio m.','Staniūnų g.','70','29','Socialinis būstas','"61','12"');
INSERT INTO "socialiniai" VALUES(115,'Panevėžio m.','Staniūnų g.','70','30','Socialinis būstas','"46','59"');
INSERT INTO "socialiniai" VALUES(116,'Panevėžio m.','Staniūnų g.','70','31','Socialinis būstas','"47','50"');
INSERT INTO "socialiniai" VALUES(117,'Panevėžio m.','Staniūnų g.','70','32','Socialinis būstas','"61','31"');
INSERT INTO "socialiniai" VALUES(118,'Panevėžio m.','Staniūnų g.','70','33','Socialinis būstas','"55','89"');
INSERT INTO "socialiniai" VALUES(119,'Panevėžio m.','Staniūnų g.','70','35','Socialinis būstas','"59','30"');
INSERT INTO "socialiniai" VALUES(120,'Panevėžio m.','Staniūnų g.','70','37','Socialinis būstas','"61','09"');
INSERT INTO "socialiniai" VALUES(121,'Panevėžio m.','Staniūnų g.','70','39','Socialinis būstas','"47','22"');
INSERT INTO "socialiniai" VALUES(122,'Panevėžio m.','Staniūnų g.','70','4','Socialinis būstas','"74','30"');
INSERT INTO "socialiniai" VALUES(123,'Panevėžio m.','Staniūnų g.','70','41','Socialinis būstas','"56','42"');
INSERT INTO "socialiniai" VALUES(124,'Panevėžio m.','Staniūnų g.','70','42','Socialinis būstas','"58','62"');
INSERT INTO "socialiniai" VALUES(125,'Panevėžio m.','Staniūnų g.','70','43','Socialinis būstas','"58','84"');
INSERT INTO "socialiniai" VALUES(126,'Panevėžio m.','Staniūnų g.','70','44','Socialinis būstas','"69','34"');
INSERT INTO "socialiniai" VALUES(127,'Panevėžio m.','Staniūnų g.','70','46','Socialinis būstas','"46','80"');
INSERT INTO "socialiniai" VALUES(128,'Panevėžio m.','Staniūnų g.','70','48','Socialinis būstas','"61','11"');
INSERT INTO "socialiniai" VALUES(129,'Panevėžio m.','Staniūnų g.','70','6','Socialinis būstas','"91','31"');
INSERT INTO "socialiniai" VALUES(130,'Panevėžio m.','Staniūnų g.','70','7','Socialinis būstas','"66','21"');
INSERT INTO "socialiniai" VALUES(131,'Panevėžio m.','Staniūnų g.','70','8','Socialinis būstas','"83','69"');
INSERT INTO "socialiniai" VALUES(132,'Panevėžio m.','Staniūnų g.','70','9','Socialinis būstas','"56','15"');
INSERT INTO "socialiniai" VALUES(133,'Panevėžio m.','Staniūnų g.','72C','305','Socialinis būstas','"35','26"');
INSERT INTO "socialiniai" VALUES(134,'Panevėžio m.','Staniūnų g.','77','311','Socialinis būstas','"32','61"');
INSERT INTO "socialiniai" VALUES(135,'Panevėžio m.','Staniūnų g.','79','18','Socialinis būstas','"37','03"');
INSERT INTO "socialiniai" VALUES(136,'Panevėžio m.','Smėlynės g.','43','1','Socialinis būstas','"33','53"');
INSERT INTO "socialiniai" VALUES(137,'Panevėžio m.','Smėlynės g.','43','4','Socialinis būstas','"60','76"');
INSERT INTO "socialiniai" VALUES(138,'Panevėžio m.','Smėlynės g.','43','6','Socialinis būstas','"25','23"');
INSERT INTO "socialiniai" VALUES(139,'Panevėžio m.','Smėlynės g.','55','29','Socialinis būstas','"44','80"');
INSERT INTO "socialiniai" VALUES(140,'Panevėžio m.','Tulpių g.','6','11','Socialinis būstas','"30','46"');
INSERT INTO "socialiniai" VALUES(141,'Panevėžio m.','Ukmergės g.','19','9','Socialinis būstas','"43','74"');
INSERT INTO "socialiniai" VALUES(142,'Panevėžio m.','Ukmergės g.','9','12','Socialinis būstas','"43','61"');
INSERT INTO "socialiniai" VALUES(143,'Panevėžio m.','Vilniaus g.','20','46','Socialinis būstas','"38','43"');
INSERT INTO "socialiniai" VALUES(144,'Panevėžio m.','Vilties g.','24','13','Socialinis būstas','"39','71"');
INSERT INTO "socialiniai" VALUES(145,'Panevėžio m.','Vilties g.','5','13','Socialinis būstas','"46','44"');
INSERT INTO "socialiniai" VALUES(146,'Panevėžio m.','Vilties g.','5','23','Socialinis būstas','"26','40"');
INSERT INTO "socialiniai" VALUES(147,'Panevėžio m.','Šv. Zitos g.','23','4','Socialinis būstas','"30','09"');
INSERT INTO "socialiniai" VALUES(148,'Panevėžio m.','Žemaičių g.','19','12','Socialinis būstas','"28','37"');
INSERT INTO "socialiniai" VALUES(149,'Panevėžio m.','Žemaičių g.','19','18','Socialinis būstas','"28','70"');
INSERT INTO "socialiniai" VALUES(150,'Panevėžio m.','Žemaičių g.','19','64','Socialinis būstas','"51','06"');
INSERT INTO "socialiniai" VALUES(151,'Panevėžio m.','Žemaičių g.','20','24','Socialinis būstas','"29','36"');
INSERT INTO "socialiniai" VALUES(152,'Panevėžio m.','Žemaičių g.','20','33','Socialinis būstas','"28','96"');
INSERT INTO "socialiniai" VALUES(153,'Panevėžio m.','Žemaičių g.','6','30','Socialinis būstas','"28','73"');
INSERT INTO "socialiniai" VALUES(154,'Panevėžio m.','Žvaigždžių g.','20','25','Socialinis būstas','"65','17"');
INSERT INTO "socialiniai" VALUES(155,'Panevėžio m.','J. Žemgulio g.','33A','3','Socialinis būstas','"63','51"');
INSERT INTO "socialiniai" VALUES(156,'Panevėžio m.','Dainavos g.','4','3','Socialinis būstas','"45','50"');
INSERT INTO "socialiniai" VALUES(157,'Panevėžio m.','Projektuotojų g.','23','26','Socialinis būstas','"50','92"');
INSERT INTO "socialiniai" VALUES(158,'Panevėžio m.','Kniaudiškių g.','10','7','Socialinis būstas','"40','16"');
INSERT INTO "socialiniai" VALUES(159,'Panevėžio m.','Kniaudiškių g.','17','35A','Socialinis būstas','"36','82"');
INSERT INTO "socialiniai" VALUES(160,'Panevėžio m.','Kniaudiškių g.','28','3','Socialinis būstas','"45','06"');
INSERT INTO "socialiniai" VALUES(161,'Panevėžio m.','Kniaudiškių g.','45','50','Socialinis būstas','"51','19"');
INSERT INTO "socialiniai" VALUES(162,'Panevėžio m.','Kniaudiškių g.','59','32','Socialinis būstas','"32','45"');
INSERT INTO "socialiniai" VALUES(163,'Panevėžio m.','Kniaudiškių g.','65','52','Socialinis būstas','"53','28"');
INSERT INTO "socialiniai" VALUES(164,'Panevėžio m.','Kniaudiškių g.','65','61','Socialinis būstas','"53','23"');
COMMIT;
